### ISSUE TITLE
Self-closing <see href=""/> tag does not correctly generate hyperlink with @href as text

### ISSUE THREAD

**Issue by heaths** [docascode/ECMA2Yaml#166]
It's valid XML doc comment to author this:

```xml
<see href="url"/>
```

Which should generate (HTML e.g.):

```html
<a href="url">url</a>
```

This does not appear to be the case, as evident in Azure SDK docs due to inadequate template applied from [here](https://github.com/docascode/ECMA2Yaml/blob/725829e35ae1a186af3b2c16a2a5601d157f4410/ECMA2Yaml/ECMAHelper/Transform/ECMADocsTransform.xsl#L112-L116).

If there is a `#text` node, that text should be used instead, i.e.:

```xml
<see href="url">text</see>
```

Should generate (HTML e.g.):

```html
<a href="url">text</a>
```

**Comment by TianqiZhang** [comment]
Thank you @heaths for reporting this, it's tracked in [AB#228057](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/228057).
