### ISSUE TITLE
Nuget not updated to latest version

### ISSUE THREAD

**Issue by joelmartinez** [docascode/ECMA2Yaml#5]
Looks like the [nuget package](https://www.nuget.org/packages/Microsoft.DocAsCode.ECMA2Yaml/) hasn't been updated in a while, currently at v1.0.105.

I'm working on a sample which shows the [mdoc](https://github.com/mono/api-doc-tools) -> EcMA2Yaml -> [docfx](http://dotnet.github.io/docfx/) workflow ... and I'd like to be able to easily script the acquisition of dependencies via nuget, and the version in nuget is throwing an exception working with a simple class and corresponding EcmaXML.

**Comment by TianqiZhang** [comment]
@joelmartinez latest nuget package is published to myget:
> "id": "Microsoft.DocAsCode.ECMA2Yaml",
> "nuget_feed": "https://www.myget.org/F/op/api/v2"

Does this feed work for you?

**Comment by joelmartinez** [comment]
Ahh, yes, thank you. It works for my purposes ... however, I'd recommend that you either start updating the regular nuget repository, or simply remove the package entirely to avoid confusion :)

Thanks!

**Comment by TianqiZhang** [comment]
@joelmartinez yes you are right, but it seems nuget.org doesn't allow me to remove the package entirely, so I guess I'll continue update nuget.org with stable packages only. Will change the CI today. Thanks!
