### ISSUE TITLE
Issue getting the XML folder when running on Mac

### ISSUE THREAD

**Issue by dend** [docascode/ECMA2Yaml#8]
When operating on an XML folder outside the realm of a repo, there is an issue where the source folder becomes empty. Specifically this in `LoadAndConvert`:

```
var rootPath = Path.GetFullPath(opt.RepoRootPath ?? opt.SourceFolder);
var xmlFolder = Path.GetFullPath(opt.SourceFolder).Replace(rootPath, "").Trim(Path.DirectorySeparatorChar);
```

Notice that if the `RootRepoPath` is empty, `SourceFolder` will be taken into consideration in `rootPath`, and subsequently erased in `xmlFolder`.

The difference here is that when running it on a *nix-based system, the paths are of the form `/test/test1` and the current `FileAccessor` doesn't seem to support them.

**Comment by dend** [comment]
Ping @TianqiZhang

**Comment by joelmartinez** [comment]
Ok … so **I think** this might be solved by some code that I always end up writing in some form or another when I'm dealing with paths in a cross-platform way:

```csharp
public static class StringExtensions
{
    public static string NormalizePath(this string path)
    {
        if (path == null) return path;	

        char otherSepChar = '/';

        if (System.IO.Path.DirectorySeparatorChar == '/')
            otherSepChar = '\\';

        if (path.Contains(otherSepChar))
            path = path.Replace(otherSepChar, System.IO.Path.DirectorySeparatorChar);	
		
        return path;
    }
}
```

The idea here is that it'll take a path, which can be using either `\` or `/` depending on what platform you're using, and will put the correct `DirectorySeparatorChar` for that platform. That way, all of the `System.IO` APIs will be working with platform-correct paths and you shouldn't encounter any problems.

**Comment by joelmartinez** [comment]
Aww, unfortunately it doesn't look like this is editable using VSMac due to the unit testing project type (vsmac currently only supports nunint and xunit project types).

![image](https://user-images.githubusercontent.com/90380/51289488-5f0aa000-19ce-11e9-9450-112f0567bb10.png)

I will try to edit in VSCode

**Comment by TianqiZhang** [comment]
@dend , thanks to @joelmartinez help, this issue has now been resolved. Could you please try the latest release and let us know if things work out for you?
